//
// Created by vito on 1.11.20.
//

#ifndef INC_03_GUESS_NUMBER_TEXT_WORLD_OBJECT_PROCESSOR_H
#define INC_03_GUESS_NUMBER_TEXT_WORLD_OBJECT_PROCESSOR_H

class TextWorldObjectProcessor {};

#endif  // INC_03_GUESS_NUMBER_TEXT_WORLD_OBJECT_PROCESSOR_H
