//
// Created by vito on 10.11.20.
//

#ifndef INC_05_GUESS_NUMBER_SYMBOL_EXPORT_H
#define INC_05_GUESS_NUMBER_SYMBOL_EXPORT_H
#ifdef DOCDOCTEST_CONFIG_IMPLEMENTATION_IN_DLL
#include "doctest.h"
//#define PEP_DECLSPEC DOCTEST_SYMBOL_EXPORT
#define PEP_DECLSPEC extern "C"
#else
#define PEP_DECLSPEC extern "C"
#endif
#endif //INC_05_GUESS_NUMBER_SYMBOL_EXPORT_H
